version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "GenASLAvatar-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aubjyjk5qnkg"
s3_prefix = "GenASLAvatar-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
